services:
  latest:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: python:3.13-slim
        INVOKEAI_VERSION: 6.9.0
    image: quickpod/invokeai:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - 9090:9090 # invokeai webui
      - 8888:8888 # jupyterlab
    # command: /bin/bash
    # tty: true
    # stdin_open: true
